load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "profgen_lib",
    srcs = ["main.go"],
    importpath = "github.com/ucpr/workspace2026/bazel_go_pgo_build/tools/profgen",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "profgen",
    embed = [":profgen_lib"],
    visibility = ["//visibility:public"],
)
